name: Fill GitHub Draft Release

on:
  push:
    branches:
      - main

permissions:
  # To create or update releases
  # https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
